class ErrorCode:

    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

    DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"

    VALIDATION_ERROR = "VALIDATION_ERROR"

    UNAUTHORIZED = "UNAUTHORIZED"

    FORBIDDEN = "FORBIDDEN"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"