"""add experience education project certification language resume_ai_analysis_model tables

Revision ID: 8daf53cb552d
Revises: 
Create Date: 2026-07-24 16:02:43.759331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8daf53cb552d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification',
    sa.Column('certification_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('certification_name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('credential_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['core.candidate.candidate_id'], ),
    sa.PrimaryKeyConstraint('certification_id'),
    schema='core'
    )
    op.create_table('education',
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=False),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('board_or_university', sa.String(length=255), nullable=True),
    sa.Column('grade_or_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['core.candidate.candidate_id'], ),
    sa.PrimaryKeyConstraint('education_id'),
    schema='core'
    )
    op.create_table('experience',
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('currently_working', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['core.candidate.candidate_id'], ),
    sa.PrimaryKeyConstraint('experience_id'),
    schema='core'
    )
    op.create_table('language',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['core.candidate.candidate_id'], ),
    sa.PrimaryKeyConstraint('language_id'),
    schema='core'
    )
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('live_url', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['core.candidate.candidate_id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    schema='core'
    )
    op.create_table('resume_ai_analysis',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='aianalysisstatus'), nullable=False),
    sa.Column('raw_resume_text', sa.Text(), nullable=True),
    sa.Column('ai_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['core.resume.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_resume_ai_analysis_analysis_id'), 'resume_ai_analysis', ['analysis_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_resume_ai_analysis_resume_id'), 'resume_ai_analysis', ['resume_id'], unique=False, schema='core')
    op.drop_table('user', schema='core')
    op.alter_column('ai_recommendation', 'recommendation_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.alter_column('ai_recommendation', 'application_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('ai_recommendation', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='ai')
    op.drop_constraint(op.f('fk_ai_application'), 'ai_recommendation', schema='ai', type_='foreignkey')
    op.create_foreign_key(None, 'ai_recommendation', 'application', ['application_id'], ['application_id'], source_schema='ai', referent_schema='core')
    op.alter_column('application', 'application_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('application', 'candidate_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('application', 'job_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('application', 'application_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('application', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('application', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.drop_constraint(op.f('uq_candidate_job'), 'application', schema='core', type_='unique')
    op.drop_constraint(op.f('fk_application_candidate'), 'application', schema='core', type_='foreignkey')
    op.drop_constraint(op.f('fk_application_job'), 'application', schema='core', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'candidate', ['candidate_id'], ['candidate_id'], source_schema='core', referent_schema='core')
    op.create_foreign_key(None, 'application', 'job', ['job_id'], ['job_id'], source_schema='core', referent_schema='core')
    op.alter_column('application_status_history', 'history_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('application_status_history', 'application_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('application_status_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.drop_constraint(op.f('fk_application_history_application'), 'application_status_history', schema='core', type_='foreignkey')
    op.create_foreign_key(None, 'application_status_history', 'application', ['application_id'], ['application_id'], source_schema='core', referent_schema='core')
    op.alter_column('candidate', 'candidate_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.drop_column('candidate', 'updated_at', schema='core')
    op.drop_column('candidate', 'created_at', schema='core')
    op.alter_column('candidate_skill', 'candidate_skill_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('candidate_skill', 'candidate_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('candidate_skill', 'skill_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('candidate_skill', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.drop_constraint(op.f('uq_candidate_skill'), 'candidate_skill', schema='core', type_='unique')
    op.drop_constraint(op.f('fk_candidate_skill_skill'), 'candidate_skill', schema='core', type_='foreignkey')
    op.drop_constraint(op.f('fk_candidate_skill_candidate'), 'candidate_skill', schema='core', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_skill', 'candidate', ['candidate_id'], ['candidate_id'], source_schema='core', referent_schema='core')
    op.create_foreign_key(None, 'candidate_skill', 'skill', ['skill_id'], ['skill_id'], source_schema='core', referent_schema='core')
    op.alter_column('company', 'company_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.drop_column('company', 'updated_at', schema='core')
    op.drop_column('company', 'created_at', schema='core')
    op.alter_column('job', 'job_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('job', 'company_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('job', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('job', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('job_skill', 'job_skill_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('job_skill', 'job_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('job_skill', 'skill_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('job_skill', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.drop_constraint(op.f('uq_job_skill'), 'job_skill', schema='core', type_='unique')
    op.drop_constraint(op.f('fk_job_skill_job'), 'job_skill', schema='core', type_='foreignkey')
    op.drop_constraint(op.f('fk_job_skill_skill'), 'job_skill', schema='core', type_='foreignkey')
    op.create_foreign_key(None, 'job_skill', 'job', ['job_id'], ['job_id'], source_schema='core', referent_schema='core')
    op.create_foreign_key(None, 'job_skill', 'skill', ['skill_id'], ['skill_id'], source_schema='core', referent_schema='core')
    op.alter_column('recruiter', 'recruiter_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('recruiter', 'company_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('recruiter', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               schema='core')
    op.alter_column('recruiter', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='core')
    op.alter_column('recruiter', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('recruiter', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('resume', 'resume_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('resume', 'candidate_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='core')
    op.alter_column('resume', 'upload_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('resume', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('resume', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('skill', 'skill_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('skill', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('skill', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('skill', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('skill', 'skill_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('resume', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('resume', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('resume', 'upload_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('resume', 'candidate_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('resume', 'resume_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('recruiter', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('recruiter', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('recruiter', 'last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               schema='core')
    op.alter_column('recruiter', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('recruiter', 'company_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('recruiter', 'recruiter_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.drop_constraint(None, 'job_skill', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'job_skill', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('fk_job_skill_skill'), 'job_skill', 'skill', ['skill_id'], ['skill_id'], source_schema='core', referent_schema='core', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_job_skill_job'), 'job_skill', 'job', ['job_id'], ['job_id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_job_skill'), 'job_skill', ['job_id', 'skill_id'], schema='core', postgresql_nulls_not_distinct=False)
    op.alter_column('job_skill', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('job_skill', 'skill_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('job_skill', 'job_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('job_skill', 'job_skill_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.alter_column('job', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('job', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('job', 'company_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('job', 'job_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.add_column('company', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False), schema='core')
    op.add_column('company', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False), schema='core')
    op.alter_column('company', 'company_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.drop_constraint(None, 'candidate_skill', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'candidate_skill', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('fk_candidate_skill_candidate'), 'candidate_skill', 'candidate', ['candidate_id'], ['candidate_id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_candidate_skill_skill'), 'candidate_skill', 'skill', ['skill_id'], ['skill_id'], source_schema='core', referent_schema='core', ondelete='RESTRICT')
    op.create_unique_constraint(op.f('uq_candidate_skill'), 'candidate_skill', ['candidate_id', 'skill_id'], schema='core', postgresql_nulls_not_distinct=False)
    op.alter_column('candidate_skill', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('candidate_skill', 'skill_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('candidate_skill', 'candidate_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('candidate_skill', 'candidate_skill_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.add_column('candidate', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False), schema='core')
    op.add_column('candidate', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False), schema='core')
    op.alter_column('candidate', 'candidate_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.drop_constraint(None, 'application_status_history', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('fk_application_history_application'), 'application_status_history', 'application', ['application_id'], ['application_id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    op.alter_column('application_status_history', 'changed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('application_status_history', 'application_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('application_status_history', 'history_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.drop_constraint(None, 'application', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'application', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('fk_application_job'), 'application', 'job', ['job_id'], ['job_id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_application_candidate'), 'application', 'candidate', ['candidate_id'], ['candidate_id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_candidate_job'), 'application', ['candidate_id', 'job_id'], schema='core', postgresql_nulls_not_distinct=False)
    op.alter_column('application', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('application', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('application', 'application_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='core')
    op.alter_column('application', 'job_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('application', 'candidate_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='core')
    op.alter_column('application', 'application_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='core')
    op.drop_constraint(None, 'ai_recommendation', schema='ai', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ai_application'), 'ai_recommendation', 'application', ['application_id'], ['application_id'], source_schema='ai', referent_schema='core', ondelete='CASCADE')
    op.alter_column('ai_recommendation', 'generated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='ai')
    op.alter_column('ai_recommendation', 'application_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('ai_recommendation', 'recommendation_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.create_table('user',
    sa.Column('user_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['ADMIN'::character varying, 'RECRUITER'::character varying]::text[])", name=op.f('chk_role')),
    sa.CheckConstraint("status::text = ANY (ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying]::text[])", name=op.f('chk_status')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='core'
    )
    op.drop_index(op.f('ix_core_resume_ai_analysis_resume_id'), table_name='resume_ai_analysis', schema='core')
    op.drop_index(op.f('ix_core_resume_ai_analysis_analysis_id'), table_name='resume_ai_analysis', schema='core')
    op.drop_table('resume_ai_analysis', schema='core')
    op.drop_table('project', schema='core')
    op.drop_table('language', schema='core')
    op.drop_table('experience', schema='core')
    op.drop_table('education', schema='core')
    op.drop_table('certification', schema='core')
    # ### end Alembic commands ###
