"""Create job_ai_analysis

Revision ID: e782c7fff6b5
Revises: 8daf53cb552d
Create Date: 2026-07-25 04:01:14.488864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e782c7fff6b5'
down_revision: Union[str, Sequence[str], None] = '8daf53cb552d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_ai_analysis',
    sa.Column('analysis_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobaianalysisstatus'), nullable=False),
    sa.Column('raw_job_text', sa.Text(), nullable=True),
    sa.Column('ai_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['core.job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_job_ai_analysis_job_id'), 'job_ai_analysis', ['job_id'], unique=False, schema='core')
    op.alter_column('resume_ai_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='core')
    op.alter_column('resume_ai_analysis', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='core')
    op.drop_index(op.f('ix_core_resume_ai_analysis_analysis_id'), table_name='resume_ai_analysis', schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_core_resume_ai_analysis_analysis_id'), 'resume_ai_analysis', ['analysis_id'], unique=False, schema='core')
    op.alter_column('resume_ai_analysis', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='core')
    op.alter_column('resume_ai_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='core')
    op.drop_index(op.f('ix_core_job_ai_analysis_job_id'), table_name='job_ai_analysis', schema='core')
    op.drop_table('job_ai_analysis', schema='core')
    # ### end Alembic commands ###
